name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install pnpm
        run: |
          npm install -g pnpm@8.15.4
          pnpm --version
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build
        run: |
          cd playground
          pnpm build
          ls -la dist
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playground/dist
          publish_branch: gh-pages
          commit_message: "Deploy site to GitHub Pages"
          force_orphan: true
